### ISSUE TITLE
Fix for better perfomance

### ISSUE THREAD

**Issue by sphynx79** [man9ourah/long-statusline#1]
First of all I wanted to congratulate you for your statusline, I am using it as a template for creating my statusline.

I belive that you can increase the performance with this FIX:
```
    function s:UpdateWinStl() " {{{
      " Status lines manager
      let l:bottomRightWin = winnr('$')
      let l:taglistWin = 0

      let l:winnr = winnr()
      for n in range(0, bottomRightWin)
        if n!=l:winnr
          let l:bufnum = winbufnr(n+1)
          let l:winbufname = bufname(l:bufnum)
          let l:winid = win_getid(n+1)
          let l:isPrv = getwinvar(n+1, "&pvw")
          let l:isHelp = getbufvar(l:winbufname, "&ft") ==# "help"
          let l:isQf = getwinvar(n+1, '&syntax') == 'qf'

          if l:isPrv || l:isHelp || l:isQf
            " Set straight line
            call setwinvar(n, '&statusline',
                  \ "%#StraightLine#%{" .
                  \ "repeat('_',\ winwidth(win_id2win(".l:winid.")))" .
                  \ "}")
          else
            " Other windows status lines
            call setwinvar(n+1, '&statusline', "%!SetStatusLine(".l:winid.")")
          end
        endif
      endfor
    endfunction   " }}}
```
In this way update the StautsLine only for curret buffer, it's not necessary update all buffer every time, i start the for loop from 0 because when startup Vim the first buffer is 0

I hope this is right, in my case work fine.

I have another question, what is work colorscheme?

Thanks so much

**Comment by man9ourah** [comment]
It is really nice of you to leave this comment, thanks!

Yes that one optimization I have tried as well, but if I remember correctly: if you have more than one window open to different buffers at the same time (vertical/horizontal split, which is my usual workflow), then the change to the git repo will not be reflected on the inactive window’s status line.. so I decided to actually leave it as is. 

Also, one other thing I thought of is batching git commands to same repo.. so if you open multiple files from the same repo, then the code should really issue one git command which should update all opened files buffers.. but I did not implement that because I felt like the impact would not be worth it since most of the operation is async.

Regarding your question, I built my own colorscheme which actually was hosted on this repo before I moved it to my private dotfiles repo.. you can still download the colorscheme and my vimrc from the history (checkout this commit ca988c44914f78b847e929be48af18459f04c1e8).. it still pretty much the same. 

Let me know if I can help more. :)

**Comment by ichelema** [comment]
Thank you very much for the explanation, indeed you are right I will look for another way to solve this problem, and then I would like to rewrite it in lua to make it even faster.

Another curiosity, do you programming for work or hobby, and in which language do you use for programming?

Thanks

**Comment by man9ourah** [comment]
> do you programming for work or hobby

Both :) 

> which language do you use for programming?

I think it depends on what are you programming, but mostly c++ for work related stuff.
